development: &default
  adapter: postgresql
  encoding: unicode
  database: twelve_stepper_development
  pool: 5
  username: postgres
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
  database: twelve_stepper_test

production:
  <<: *default
  database: twelve_stepper_production
