development:
  adapter: postgresql
  encoding: unicode
  database: twelve_stepper_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twelve_stepper_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: twelve_stepper_production
  pool: 5
  username: twelve_stepper
  password:
